WindySong.NoteBook.Web/Controllers/AdminSysConfigController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using WindySong.NoteBook.Web.Common;
using WindySong.NoteBook.App.Interfaces;
using WindySong.NoteBook.App.ViewModels.Admin;
using WindySong.NoteBook.App.ViewModels.Json;

namespace WindySong.NoteBook.Web.Controllers
{
    //权限验证
    [Authorize]
    //属性过滤器
    [FieldFilter]
    public class AdminSysConfigController : ManageController
    {
        //用户登录业务接口
        private ISysConfigAppService _sysConfig;
        private ICacheService _cache;
        public AdminSysConfigController(ISysConfigAppService loginApp, ICacheService cashe)
        {
            this._sysConfig = loginApp;
            this._cache = cashe;
        }
        public IActionResult Index()
        {
            SysConfigModel model = _sysConfig.GetSysConfig();
            return View(model);
        }
        //Token验证，防止CSRF XSS攻击
        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Index(SysConfigModel model)
        {
            //判断数据是否合法
            if (!ModelState.IsValid)
            {
                
                return Json(this.GetSwalJson(0, "非法数据", this.IfModelStateString(), "error"));
            }
            if(string.IsNullOrEmpty(model.cdn))
            {
                model.cdn = "";
            }
            if(_sysConfig.SetSysConfig(model))
            {
                //更新静态类数据
                _cache.ReplaceAsync("sitename", model.siteName);
                _cache.ReplaceAsync("sitekey", model.siteKeyWords);
                _cache.ReplaceAsync("sitedes", model.siteDescription);
                _cache.ReplaceAsync("cdn", model.cdn);

                return Json(this.GetSwalJson(1, "保存成功", "success", "success"));
            }
            else
            {
                return Json(this.GetSwalJson(0, "保存失败", "error", "error"));
            }
        }
        public IActionResult StaticIndex()
        {
            return View();
        }

    }
}

WindySong.NoteBook.Web/ViewComponents/HeadViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WindySong.NoteBook.App.Interfaces;

namespace WindySong.NoteBook.Web.ViewComponents
{
    public class HeadViewComponent : ViewComponent
    {
        private ICacheService _cache;
        public HeadViewComponent(ICacheService cashe)
        {
            this._cache = cashe;
        }
        public IViewComponentResult Invoke()
        {
            ViewData["sitename"] = _cache.Get("sitename").ToString();
            ViewData["sitekey"] = _cache.Get("sitekey").ToString();
            ViewData["sitedes"] = _cache.Get("sitedes").ToString();
            ViewData["cdn"] = _cache.Get("cdn").ToString();
            return View();
        }
    }
}

WindySong.NoteBook.Web/ViewComponents/StyleViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WindySong.NoteBook.App.Interfaces;

namespace WindySong.NoteBook.Web.ViewComponents
{
    public class StyleViewComponent : ViewComponent
    {
        private ICacheService _cache;
        public StyleViewComponent(ICacheService cashe)
        {
            this._cache = cashe;
        }
        public IViewComponentResult Invoke()
        {
            ViewData["cdn"] = _cache.Get("cdn").ToString();
            return View();
        }
    }
}

WindySong.NoteBook.Web/Views/AdminSysConfig/Index.cshtml
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@using WindySong.NoteBook.Web.Common
@model WindySong.NoteBook.App.ViewModels.Admin.SysConfigModel
<!DOCTYPE html>
<html>
<head>
    @await Component.InvokeAsync("Head")
    @await Component.InvokeAsync("Style")
</head>
<body class="gray-bg">
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>网站信息配置 <small></small></h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <form method="post" id="myform" class="form-horizontal" asp-controller="AdminSysConfig" asp-action="Index">
                            <div class="form-group">
                                <label class="col-sm-2 control-label">网站名称</label>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <!--使用form-group包裹表单，才能正确的显示前端验证提示信息-->
                                        <input type="text" class="form-control" asp-for="siteName">
                                    </div>                                   
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Keywords</label>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <input type="text" class="form-control" asp-for="siteKeyWords">
                                    </div>                                    
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Description</label>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <input type="text" class="form-control" asp-for="siteDescription">
                                    </div>  
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">CDN信息</label>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <input type="text" class="form-control" asp-for="cdn">
                                        <span class="help-block m-b-none"><i class="fa fa-info-circle"></i> 如果没有CDN则留空，如果使用cdn，请在服务器对子目录wwwroot绑定回源域名，然后cdn指定此域名，这里就填写cdn域名，如http://cdn.airuxu.cn</span>
                                    </div>
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-2">
                                    <button id="submitForm" class="btn btn-primary" type="button">保存内容</button>
                                </div>
                            </div>
                        </form>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function () {
            //文档加载完成后添加保存按钮的单击事件
            $("#submitForm").click(function () {
                $('#myform').submit();  
            });
            
        });

        $.validator.setDefaults({
            highlight: function (element) {
                $(element).closest('.form-group').removeClass('has-success').addClass('has-error');
            },
            success: function (element) {
                element.closest('.form-group').removeClass('has-error').addClass('has-success');
            },
            errorElement: "span",
            errorPlacement: function (error, element) {
                if (element.is(":radio") || element.is(":checkbox")) {
                    error.appendTo(element.parent().parent().parent());
                } else {
                    error.appendTo(element.parent());
                }
            },
            errorClass: "help-block m-b-none",
            validClass: "help-block m-b-none"


        });
        //表单验证
        // validate signup form on keyup and submit
        var icon = "<i class='fa fa-times-circle'></i> ";
        $("#myform").validate({
            rules: {
                siteName: {
                    required: true,
                    minlength: 3,
                    maxlength: 30
                },
                siteKeyWords: {
                    required: true,
                    minlength: 3,
                    maxlength: 50
                },
                siteDescription: {
                    required: true,
                    minlength: 3,
                    maxlength: 50
                }
            },
            messages: {
                siteName: {
                    required: icon + "请输入站点名称",
                    minlength: icon + "站点名称必须3个字符以上",
                    maxlength: icon + "站点名称必须30个字符以下"
                },
                siteKeyWords: {
                    required: icon + "请输入站点关键字",
                    minlength: icon + "站点关键字必须3个字符以上",
                    maxlength: icon + "站点关键字必须50个字符以下"
                }
                ,
                siteDescription: {
                    required: icon + "请输入站点描述",
                    minlength: icon + "站点描述必须3个字符以上",
                    maxlength: icon + "站点描述必须50个字符以下"
                }
            },
            //表单验证成功执行方法
            submitHandler: function (form) {
                $.ajax({
                    url: '/AdminSysConfig/Index',
                    type: 'post',
                    dataType: 'json',
                    data: $("#myform").serialize(),
                    cache: false,
                    error: erryFunction,  //错误执行方法    
                    success: succFunction//成功执行方法
                });
                function erryFunction() {
                    PopupDia("请求失败", "error", "error");
                }
                function succFunction(data) {
                    //获取返回的json数据
                    var state = data.state;
                    var title = data.title;
                    var text = data.text;
                    var type = data.type;
                    //console.log(data);
                    PopupDia(title, text, type);
                }
                function PopupDia(strTitle, strText, strType) {
                    var iconnumber;
                    if (strType == "success") {
                        iconnumber = 1;
                    }
                    else if (strType == "error") {
                        iconnumber = 2;
                    }
                    else {
                        iconnumber = 1;
                    }
                    layer.msg(strTitle + ',' + strText, { icon: iconnumber, offset: 't' });
                }
            }  
        });
    </script>
</body>
</html>

WindySong.NoteBook.Web/Views/AdminSysConfig/StaticIndex.cshtml
@using WindySong.NoteBook.Web.Common
<!DOCTYPE html>
<html>
<head>
    @await Component.InvokeAsync("Head")
    @await Component.InvokeAsync("Style")
</head>
<body class="gray-bg">
    <div class="row  border-bottom white-bg dashboard-header">

        <form method="post" id="myform" class="form-horizontal">
            <div class="hr-line-dashed"></div>
            <div class="form-group">
                <div class="col-sm-4 col-sm-offset-2">
                    <button id="submitForm" class="btn btn-success btn-lg" type="button">生成首页静态文件</button>
                </div>
            </div>
        </form>
    </div>
    <script type="text/javascript">
            function PopupDia(strTitle, strText, strType) {
                var iconnumber;
                if (strType == "success") {
                    iconnumber = 1;
                }
                else if (strType == "error") {
                    iconnumber = 2;
                }
                else {
                    iconnumber = 1;
                }
                layer.msg(strTitle + ',' + strText, { icon: iconnumber, offset: 't' });
            }
            $(document).ready(function () {
                //文档加载完成后添加保存按钮的单击事件
                $("#submitForm").click(function () {
                    $.ajax({
                        url: '/Home/Default',
                        type: 'get',
                        dataType: 'json',
                        data: $("#myform").serialize(),
                        cache: false,
                        error: erryFunction,  //错误执行方法
                        success: succFunction//成功执行方法
                    });
                    function erryFunction() {
                        PopupDia("请求失败", "error", "error");
                    }
                    function succFunction(data) {
                        //获取返回的json数据
                        //获取返回的json数据
                        var state = data.state;
                        var title = data.title;
                        var text = data.text;
                        var type = data.type;

                        PopupDia(title, text, type);
                    }
                });

            });
    </script>
</body>
</html>