WindySong.NoteBook.Web/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WindySong.NoteBook.Web.Common;
using WindySong.NoteBook.App.ViewModels.Admin;
using WindySong.NoteBook.App.Interfaces;
using WindySong.NoteBook.App.Entity;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using WindySong.NoteBook.App;
using Microsoft.AspNetCore.Http;
using Common;

namespace WindySong.NoteBook.Web.Controllers
{
    //属性过滤器
    [FieldFilter]
    public class LoginController : BaseController
    {
        private ICacheService _cache;
        //用户登录业务接口
        private ILoginAppService _loginApp;
        public LoginController(ILoginAppService loginApp, ICacheService cashe)
        {
            this._loginApp = loginApp;
            this._cache = cashe;
        }

        //[Route("Login")] /*路由特性定义 这个路由特性表示 URL/Login 将访问到这个Action*/
        [HttpGet]
        public IActionResult Index(String ReturnUrl)
        {
            ViewData["cdn"] = _cache.Get("cdn").ToString();
            //如果用户没有登录
            if (!User.Identity.IsAuthenticated)
            {
                //URL不为空
                if (!string.IsNullOrEmpty(ReturnUrl))
                {
                    ViewBag.returnUrl = ReturnUrl;
                }
            }
            else
            {
                if (!string.IsNullOrEmpty(ReturnUrl))
                {
                    return new RedirectResult(ReturnUrl);
                }
                else
                {
                    return RedirectToRoute(new { controller = "Admin", action = "Index" });
                }
                
            }
            
            return View();
        }

        //Token验证，防止CSRF XSS攻击
        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Index(LoginModel loginModel)
        {
            ViewData["cdn"] = _cache.Get("cdn").ToString();
            //验证模型的数据验证是否通过
            if (!ModelState.IsValid)
            {
                this.IfModelStateViewData();
                return View();
            }
            //判断验证码是否合法
            string clientValidCode = HttpContext.Session.GetString("ValidCode");
            if(loginModel.validateCode != clientValidCode)
            {
                ViewData["formError"] = "验证码错误!";
                return View();
            }

            //登录验证方法
            LoginModel _logigModel = _loginApp.UserLogin(loginModel);
            //登录失败
            if(_logigModel == null)
            {
                ViewData["formError"] = "用户名密码失败!";
                return View();
            }
            else
            {
                //添加cookies
                ClaimsIdentity identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
                identity.AddClaim(new Claim(ClaimTypes.Name, _logigModel.name));
                identity.AddClaim(new Claim(ClaimTypes.Sid, _logigModel.id.ToString()));
                //设置有效期
                HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(identity), new AuthenticationProperties
                {
                    // 持久保存
                    IsPersistent = true,

                    // 指定过期时间AddMinutes 添加分钟
                    //ExpiresUtc = DateTime.UtcNow.AddMinutes(20)\
                    // 指定过期时间AddMinutes 添加天
                    ExpiresUtc = DateTime.UtcNow.AddDays(7)
                });
                if (!string.IsNullOrEmpty(loginModel.returnUrl))
                {
                    //返回URL
                    return new RedirectResult(loginModel.returnUrl);
                }
                else
                {
                    return RedirectToRoute(new { controller = "Admin", action = "Index" });//跳转到其他controller RedirectToAction("Admin/Index");//调整到其他Action
                }
                
            }
        }

        public IActionResult ValidateCode()
        {
            string code = Commonly.GetRandomString(4);
            HttpContext.Session.SetString("ValidCode", code);
            return File(this.GetValidCodeByte(code), "image/png");
        }

    }
}

WindySong.NoteBook.Web/ViewComponents/HeadViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WindySong.NoteBook.App.Interfaces;

namespace WindySong.NoteBook.Web.ViewComponents
{
    public class HeadViewComponent : ViewComponent
    {
        private ICacheService _cache;
        public HeadViewComponent(ICacheService cashe)
        {
            this._cache = cashe;
        }
        public IViewComponentResult Invoke()
        {
            ViewData["sitename"] = _cache.Get("sitename").ToString();
            ViewData["sitekey"] = _cache.Get("sitekey").ToString();
            ViewData["sitedes"] = _cache.Get("sitedes").ToString();
            ViewData["cdn"] = _cache.Get("cdn").ToString();
            return View();
        }
    }
}

WindySong.NoteBook.Web/ViewComponents/LoginViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WindySong.NoteBook.App.Interfaces;

namespace WindySong.NoteBook.Web.ViewComponents
{
    public class LoginViewComponent : ViewComponent
    {
        private ICacheService _cache;
        public LoginViewComponent(ICacheService cashe)
        {
            this._cache = cashe;
        }
        public IViewComponentResult Invoke()
        {
            ViewData["cdn"] = _cache.Get("cdn").ToString();
            return View();
        }
    }
}

WindySong.NoteBook.Web/Views/Login/Index.cshtml
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@model WindySong.NoteBook.App.ViewModels.Admin.LoginModel
@using WindySong.NoteBook.Web.Common
<!DOCTYPE html>
<html lang="en">
<head>
    @await Component.InvokeAsync("Head")
    @await Component.InvokeAsync("Login")    
    <style type="text/css">
        body.signin {
            background: #18c8f6;
            height: auto;
            background: url("@ViewData["cdn"]/img/login-background.jpg") no-repeat center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
            color: rgba(255,255,255,.95);
        }
        .signinpanel .uname {
            background: #fff url(@ViewData["cdn"]/img/user.png) no-repeat 95% center;
            color: #333;
        }

        .signinpanel .pword {
            background: #fff url(@ViewData["cdn"]/img/locked.png) no-repeat 95% center;
            color: #333;
        }
    </style>
    <script>
        if (window.top !== window.self) {
            window.top.location = window.location;
        }
    </script>
</head>
<body class="signin">
    <div class="signinpanel">
        <div class="row">
            <div class="col-sm-7">
                <div class="signin-info">
                    <div class="logopanel m-b">
                        <h1>孤灯寒照雨，深竹暗浮烟。 </h1>
                    </div>
                    <div class="m-b"></div>

                </div>
            </div>
            <div class="col-sm-5">
                <!--使用了asp-controller asp-action 标签 前端就会自动生成Token-->
                <form id="loginForm" method="post" asp-controller="Login" asp-action="Index">
                    <h4 class="no-margins">登录：</h4>
                    <div class="form-group"><!--使用form-group包裹表单，才能正确的显示前端验证提示信息-->
                        <input type="text" class="form-control uname" placeholder="用户名" asp-for="name" />
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control pword m-b" placeholder="密码" asp-for="password" />
                        <input type="hidden" value="@ViewBag.returnUrl" name="returnUrl" />
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control uname"  asp-for="validateCode" />
                    </div>
                    <div class="form-group">
                        <img id="imgVerify" src="/Login/ValidateCode" alt="看不清？点击更换" onclick="this.src = this.src + '?'" style="vertical-align:middle;" />
                    </div>
                    <button class="btn btn-success btn-block" type="submit">登录</button>
                    <br />
                    <song class="text-warning">@Html.Raw(ViewData["formError"]) </song>
                </form>
            </div>
        </div>
        <div class="signup-footer">
            <div class="pull-left">
                &copy; @System.DateTime.Now.Year All Rights Reserved.
            </div>
        </div>
    </div>
    <script>
        $.validator.setDefaults({
            highlight: function (element) {
                $(element).closest('.form-group').removeClass('has-success').addClass('has-error');
            },
            success: function (element) {
                element.closest('.form-group').removeClass('has-error').addClass('has-success');
            },
            errorElement: "span",
            errorPlacement: function (error, element) {
                if (element.is(":radio") || element.is(":checkbox")) {
                    error.appendTo(element.parent().parent().parent());
                } else {
                    error.appendTo(element.parent());
                }
            },
            errorClass: "help-block m-b-none",
            validClass: "help-block m-b-none"


        });

        // validate signup form on keyup and submit
        var icon = "<i class='fa fa-times-circle'></i> ";
        $("#loginForm").validate({
            rules: {
                name: {
                    required: true,
                    minlength: 3,
                    maxlength: 10
                },
                password: {
                    required: true,
                    minlength: 6,
                    maxlength: 16
                },
                validateCode: {
                    required: true
                }
            },
            messages: {
                name: {
                    required: icon + "请输入您的用户名",
                    minlength: icon + "用户名必须3个字符以上",
                    maxlength: icon + "用户名必须10个字符以下"
                },
                password: {
                    required: icon + "请输入您的密码",
                    minlength: icon + "密码必须6个字符以上",
                    maxlength: icon + "密码必须16个字符以下"
                },
                validateCode: {
                    required: icon + "请输入验证码"
                }
            }
        });
    </script>

</body>
</html>