WindySong.NoteBook.Web/Controllers/AdminUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WindySong.NoteBook.Web.Common;
using Microsoft.AspNetCore.Authorization;
using WindySong.NoteBook.App.Interfaces;
using WindySong.NoteBook.App.ViewModels.Admin;
using WindySong.NoteBook.App.ViewModels.Json;
using Microsoft.AspNetCore.Http;
using System.Net.Http.Headers;
using System.IO;
using System.Security.Claims;
using Common;
using Microsoft.Extensions.Caching.Memory;

namespace WindySong.NoteBook.Web.Controllers
{
    //权限验证
    [Authorize]
    //属性过滤器
    [FieldFilter]
    public class AdminUserController : ManageController
    {
        //用户操作接口
        private IUserAppService _userApp;
        public AdminUserController(IUserAppService userApp)
        {
            this._userApp = userApp;
        }
        public IActionResult Password()
        {
            return View();
        }
        //Token验证，防止CSRF XSS攻击
        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Password(UpdatePasswordModel model)
        {
            var jsonResults = new JsonResultsString();
            //判断数据是否合法
            if (!ModelState.IsValid)
            {
                return Json(this.GetSwalJson(0, "非法数据", this.IfModelStateString(), "error"));
            }
            int i = 0;
            i = _userApp.UpdatePassword(User.Identity.Name, model);
            switch (i)
            {
                case 1:
                    jsonResults = this.GetSwalJson(1, "更新成功", "success", "success");
                    break;
                case 0:
                    jsonResults = this.GetSwalJson(0, "更新失败", "error", "error");
                    break;
                case -1:
                    jsonResults = this.GetSwalJson(-1, "更新失败,用户不存在", "error", "error");
                    break;
                case -2:
                    jsonResults = this.GetSwalJson(-2, "更新失败,旧密码错误", "error", "error");
                    break;
            }
            return Json(jsonResults);
        }

        public IActionResult UserPhoto()
        {
            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult UserPhoto(IFormFile userPhoto,int dataX,int dataY,int dataWidth,int dataHeight)
        {
            string originalPath = Directory.GetCurrentDirectory() + @"/Upload/UserPhoto/";
            string thumbnailPath = Directory.GetCurrentDirectory() + @"/Upload/UserPhotoThumbnail/";
            string cutPath = Directory.GetCurrentDirectory() + @"/Upload/UserPhotoCut/";
            var jsonResults = new JsonResultsString();
            // 文件大小
            long size = 0;
            // 原文件名（包括路径）
            var filename = ContentDispositionHeaderValue.Parse(userPhoto.ContentDisposition).FileName;
            // 扩展名
            var extName = filename.Substring(filename.LastIndexOf('.')).Replace("\"", "").ToLower();
            //判断后缀是否合法
            if(extName != ".jpg" && extName != ".png" && extName != ".gif")
            {
                return Json(this.GetSwalJson(0, "只能上传图片格式", "error", "error"));
            }
            // 设置文件大小
            size += userPhoto.Length;
            //判断文件大小
            if (size < 1)
            {
                return Json(this.GetSwalJson(0, "图片过小", "error", "error"));
            }

            // 新文件名
            string shortfilename = $"{Guid.NewGuid()}{extName}";
            // 新文件名（包括路径）
            filename = originalPath + shortfilename;
            
            


            Stream stream = userPhoto.OpenReadStream();
            //通过byte正确安全的判断上传文件格式 
            //第一种方法
            byte[] fileByte = new byte[2];//contentLength，这里我们只读取文件长度的前两位用于判断就好了，这样速度比较快，剩下的也用不到。
            stream.Read(fileByte, 0, 2);//contentLength，还是取前两位
            string fileFlag = ""; 
            if (fileByte != null && fileByte.Length > 0)//图片数据是否为空
            {
                fileFlag = fileByte[0].ToString() + fileByte[1].ToString();
            }
            //说明255216是jpg;7173是gif;6677是BMP,13780是PNG;7790是exe,8297是rar 
            string[] fileTypeStr = { "255216", "7173", "13780" };//对应的图片格式jpg,gif,bmp,png
            if (!fileTypeStr.Contains(fileFlag))
            {
                return Json(this.GetSwalJson(0, "只能上传图片格式", "error", "error"));
            }
            ////第二种方法
            //BinaryReader r = new BinaryReader(stream);
            //string fileclass = "";
            ////这里的位长要具体判断
            //for (int i = 0; i < 2; i++)
            //{
            //    fileclass += r.ReadByte().ToString();
            //}
            //r.Close();
            //string[] fileTypeStr = { "255216", "7173", "13780" };//对应的图片格式jpg,gif,bmp,png
            //if (!fileTypeStr.Contains(fileclass))
            //{
            //    return Json(this.GetSwalJson(-1, "只能上传图片格式", "error", "error"));
            //}


            // 创建新文件
            using (FileStream fs = System.IO.File.Create(filename))
            {
                try
                {
                    // 复制文件
                    userPhoto.CopyTo(fs);
                    // 清空缓冲区数据
                    fs.Flush();
                }
                catch (Exception e)
                {
                    jsonResults = this.GetSwalJson(0, "上传失败，服务器保存错误", "error", "error");
                }

            }
            try
            {
                bool cut = false;
                cut = Images.CutImage(dataX, dataY, dataWidth, dataHeight, filename, cutPath + shortfilename);

                bool thumbnail = false;
                thumbnail = Images.ThumbnailImage(cutPath + shortfilename, thumbnailPath+ shortfilename, 64, 64);
                if(thumbnail)
                {
                    _userApp.SetUserPhoto(int.Parse(User.FindFirstValue(ClaimTypes.Sid)), shortfilename);
                    jsonResults = this.GetSwalJson(1, "上传成功", "success", "success");
                }
                else
                {
                    jsonResults = this.GetSwalJson(0, "上传失败，缩图失败", "error", "error");
                }
                
            }
            catch (Exception e)
            {
                jsonResults = this.GetSwalJson(0, "上传失败，图片处理异常", "error", "error");
            }

            return Json(jsonResults);
        }
    }
}

WindySong.NoteBook.Web/ViewComponents/HeadViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WindySong.NoteBook.App.Interfaces;

namespace WindySong.NoteBook.Web.ViewComponents
{
    public class HeadViewComponent : ViewComponent
    {
        private ICacheService _cache;
        public HeadViewComponent(ICacheService cashe)
        {
            this._cache = cashe;
        }
        public IViewComponentResult Invoke()
        {
            ViewData["sitename"] = _cache.Get("sitename").ToString();
            ViewData["sitekey"] = _cache.Get("sitekey").ToString();
            ViewData["sitedes"] = _cache.Get("sitedes").ToString();
            ViewData["cdn"] = _cache.Get("cdn").ToString();
            return View();
        }
    }
}

WindySong.NoteBook.Web/ViewComponents/StyleViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WindySong.NoteBook.App.Interfaces;

namespace WindySong.NoteBook.Web.ViewComponents
{
    public class StyleViewComponent : ViewComponent
    {
        private ICacheService _cache;
        public StyleViewComponent(ICacheService cashe)
        {
            this._cache = cashe;
        }
        public IViewComponentResult Invoke()
        {
            ViewData["cdn"] = _cache.Get("cdn").ToString();
            return View();
        }
    }
}

WindySong.NoteBook.Web/Views/AdminUser/Password.cshtml
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@using WindySong.NoteBook.Web.Common
@model WindySong.NoteBook.App.ViewModels.Admin.UpdatePasswordModel
@using WindySong.NoteBook.Web.Common
<!DOCTYPE html>
<html>
<head>
    @await Component.InvokeAsync("Head")
    @await Component.InvokeAsync("Style")
</head>
<body class="gray-bg">
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>修改密码 <small></small></h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <form method="post" id="myform" class="form-horizontal" asp-controller="AdminUser" asp-action="Password">
                            <div class="form-group">
                                <label class="col-sm-2 control-label">旧密码</label>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <!--使用form-group包裹表单，才能正确的显示前端验证提示信息-->
                                        <input type="password" class="form-control" asp-for="oldPassword">
                                    </div>
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">新密码</label>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <input type="password" class="form-control" asp-for="newPassword">
                                    </div>
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">确认新密码</label>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <input type="password" class="form-control" asp-for="confirmNewPassword">
                                    </div>
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-2">
                                    <button id="submitForm" class="btn btn-primary" type="button">保存内容</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function () {
            //文档加载完成后添加保存按钮的单击事件
            $("#submitForm").click(function () {
                $('#myform').submit();
            });

        });

        $.validator.setDefaults({
            highlight: function (element) {
                $(element).closest('.form-group').removeClass('has-success').addClass('has-error');
            },
            success: function (element) {
                element.closest('.form-group').removeClass('has-error').addClass('has-success');
            },
            errorElement: "span",
            errorPlacement: function (error, element) {
                if (element.is(":radio") || element.is(":checkbox")) {
                    error.appendTo(element.parent().parent().parent());
                } else {
                    error.appendTo(element.parent());
                }
            },
            errorClass: "help-block m-b-none",
            validClass: "help-block m-b-none"


        });
        //表单验证
        // validate signup form on keyup and submit
        var icon = "<i class='fa fa-times-circle'></i> ";
        $("#myform").validate({
            rules: {
                oldPassword: {
                    required: true,
                    minlength: 6,
                    maxlength: 16
                },
                newPassword: {
                    required: true,
                    minlength: 6,
                    maxlength: 16
                },
                confirmNewPassword: {
                    equalTo: "#newPassword"
                }
            },
            messages: {
                oldPassword: {
                    required: icon + "请输入旧密码",
                    minlength: icon + "旧密码必须6个字符以上",
                    maxlength: icon + "旧密码必须16个字符以下"
                },
                newPassword: {
                    required: icon + "请输入新密码",
                    minlength: icon + "新密码必须6个字符以上",
                    maxlength: icon + "新密码必须16个字符以下"
                }
                ,
                confirmNewPassword: {
                    equalTo: icon + "两次新密码输入不一致"
                }
            },
            //表单验证成功执行方法
            submitHandler: function (form) {
                $.ajax({
                    url: '/AdminUser/Password',
                    type: 'post',
                    dataType: 'json',
                    data: $("#myform").serialize(),
                    cache: false,
                    error: erryFunction,  //错误执行方法
                    success: succFunction//成功执行方法
                });
                function erryFunction() {
                    PopupDia("请求失败", "error", "error");
                }
                function succFunction(data) {
                    //获取返回的json数据
                    //获取返回的json数据
                    var state = data.state;
                    var title = data.title;
                    var text = data.text;
                    var type = data.type;

                    PopupDia(title, text, type);
                }
                function PopupDia(strTitle, strText, strType) {
                    var iconnumber;
                    if (strType == "success") {
                        iconnumber = 1;
                    }
                    else if (strType == "error") {
                        iconnumber = 2;
                    }
                    else {
                        iconnumber = 1;
                    }
                    layer.msg(strTitle + ',' + strText, { icon: iconnumber, offset: 't' });
                }
            }
        });
    </script>
</body>
</html>

WindySong.NoteBook.Web/Views/AdminUser/UserPhoto.cshtml
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@using WindySong.NoteBook.Web.Common
@model WindySong.NoteBook.App.ViewModels.Admin.UpdatePasswordModel
@using WindySong.NoteBook.Web.Common
<!DOCTYPE html>
<html>
<head>
    @await Component.InvokeAsync("Head")
    @await Component.InvokeAsync("Style")
    <style>
        .img-preview {
            width: 100px;
            height: 100px;
            overflow: hidden;
        }
    </style>
</head>
<body class="gray-bg">
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>头像上传 <small></small></h5>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="container">
                @*<div class="row">
                        <div class="col-sm-12 text-center">
                            <label for="input" class="btn btn-danger" id="">
                                <span>选择图片</span>
                                <input type="file" id="input" class="sr-only">
                            </label>
                        </div>
                    </div>*@
                <div class="row">
                    <div class="col-sm-6 col-sm-offset-2">
                        <img src="" id="photo">
                    </div>
                    <div class="col-sm-2">
                        <div>
                            <p>
                                预览(100*100)：
                            </p>
                            <div class="img-preview">
                            </div>
                        </div>
                        <div class="docs-data">
                            <div class="input-group">
                                <label class="input-group-addon" for="dataX">X</label>
                                <input class="form-control" id="dataX" name="dataX" type="text" placeholder="x">
                                <span class="input-group-addon">px</span>
                            </div>
                            <div class="input-group">
                                <label class="input-group-addon" for="dataY">Y</label>
                                <input class="form-control" id="dataY" name="dataY" type="text" placeholder="y">
                                <span class="input-group-addon">px</span>
                            </div>
                            <div class="input-group">
                                <label class="input-group-addon" for="dataWidth">Width</label>
                                <input class="form-control" id="dataWidth" name="dataWidth" type="text" placeholder="width">
                                <span class="input-group-addon">px</span>
                            </div>
                            <div class="input-group">
                                <label class="input-group-addon" for="dataHeight">Height</label>
                                <input class="form-control" id="dataHeight" name="dataHeight" type="text" placeholder="height">
                                <span class="input-group-addon">px</span>
                            </div>
                            <div class="input-group">
                                <label class="input-group-addon" for="dataRotate">Rotate</label>
                                <input class="form-control" id="dataRotate" type="text" placeholder="rotate">
                                <span class="input-group-addon">deg</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="ibox-content">
                <form method="post" id="myform" class="form-horizontal" asp-controller="AdminUser" asp-action="UserPhoto" enctype="multipart/form-data">
                    <div class="form-group">
                        <label class="col-sm-2 control-label">选择文件</label>
                        <div class="col-sm-10">
                            <div class="form-group">
                                <!--使用form-group包裹表单，才能正确的显示前端验证提示信息-->
                                <input type="file" class="filestyle" data-buttonName="btn-primary" id="userPhoto" name="userPhoto">
                                <script>$(":file").filestyle({ buttonName: "btn-primary", buttonBefore: true });</script>
                                @*<input type="file"  id="userPhoto" name="userPhoto">*@
                            </div>
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="form-group">
                        <div class="col-sm-4 col-sm-offset-2">
                            <button id="submitForm" class="btn btn-primary" type="button">保存内容</button>
                        </div>
                    </div>
                </form>

            </div>
        </div>

    </div>
    <script>
        $(function () {
            initCropper($('#photo'), $('#userPhoto'));
        });
        // 修改自官方demo的js
        var initCropper = function (img, input) {
            var $image = img;
            var options = {
                aspectRatio: 1 / 1, // 纵横比
                viewMode: 2,
                preview: '.img-preview', // 预览图的class名
                crop: function (data) {
                    $("#dataX").val(Math.round(data.x));
                    $("#dataY").val(Math.round(data.y));
                    $("#dataHeight").val(Math.round(data.height));
                    $("#dataWidth").val(Math.round(data.width));
                    $("#dataRotate").val(Math.round(data.rotate));
                    //console.log(Math.round(data.x));
                    //console.log(Math.round(data.y));
                    //console.log(Math.round(data.height));
                    //console.log(Math.round(data.width));
                    //console.log(Math.round(data.rotate));
                }
            };
            $image.cropper(options);
            var $inputImage = input;
            var uploadedImageURL;
            if (URL) {
                // 给input添加监听
                $inputImage.change(function () {
                    var files = this.files;
                    var file;
                    if (!$image.data('cropper')) {
                        return;
                    }
                    if (files && files.length) {
                        file = files[0];
                        // 判断是否是图像文件
                        if (/^image\/\w+$/.test(file.type)) {
                            // 如果URL已存在就先释放
                            if (uploadedImageURL) {
                                URL.revokeObjectURL(uploadedImageURL);
                            }
                            uploadedImageURL = URL.createObjectURL(file);
                            // 销毁cropper后更改src属性再重新创建cropper
                            $image.cropper('destroy').attr('src', uploadedImageURL).cropper(options);
                            //$inputImage.val('');
                        } else {
                            PopupDia("请选择一个图像文件", "error", "error");
                            $inputImage.val('');
                        }
                    }
                });
            } else {
                $inputImage.prop('disabled', true).addClass('disabled');
            }
        }

    </script>
    <script>
        $(document).ready(function () {
            //文档加载完成后添加保存按钮的单击事件
            $("#submitForm").click(function () {
                $('#myform').submit();
            });

        });

        function PopupDia(strTitle, strText, strType) {
            var iconnumber;
            if (strType == "success") {
                iconnumber = 1;
            }
            else if (strType == "error") {
                iconnumber = 2;
            }
            else {
                iconnumber = 1;
            }
            layer.msg(strTitle + ',' + strText, { icon: iconnumber, offset: 't' });
        }

        $.validator.setDefaults({
            highlight: function (element) {
                $(element).closest('.form-group').removeClass('has-success').addClass('has-error');
            },
            success: function (element) {
                element.closest('.form-group').removeClass('has-error').addClass('has-success');
            },
            errorElement: "span",
            errorPlacement: function (error, element) {
                if (element.is(":radio") || element.is(":checkbox")) {
                    error.appendTo(element.parent().parent().parent());
                } else {
                    error.appendTo(element.parent());
                }
            },
            errorClass: "help-block m-b-none",
            validClass: "help-block m-b-none"


        });
        //表单验证
        // validate signup form on keyup and submit
        var icon = "<i class='fa fa-times-circle'></i> ";
        $("#myform").validate({
            rules: {
                userPhoto: {
                    required: true
                }
            },
            messages: {
                userPhoto: {
                    required: icon + "请选择文件"
                }
            },
            //表单验证成功执行方法
            submitHandler: function (form) {
                // js 获取文件对象
                var fileObj = document.getElementById("userPhoto").files[0];
                if (typeof (fileObj) == "undefined" || fileObj.size <= 0) {
                    PopupDia("请选择文件", "error", "error");
                    return;
                }
                
                var formFile = new FormData();
                //添加token
                formFile.append("__RequestVerificationToken", $("input[name='__RequestVerificationToken'] ").val());
                formFile.append("dataX", $("input[name='dataX'] ").val());
                formFile.append("dataY", $("input[name='dataY'] ").val());
                formFile.append("dataWidth", $("input[name='dataWidth'] ").val());
                formFile.append("dataHeight", $("input[name='dataHeight'] ").val());
                //加入文件对象
                formFile.append("userPhoto", fileObj);
                var data = formFile;
                $.ajax({
                    url: '/AdminUser/UserPhoto',
                    cache: false,//上传文件无需缓存
                    processData: false,//用于对data参数进行序列化处理 这里必须false
                    contentType: false, //必须
                    type: 'post',
                    dataType: 'json',
                    data: data,
                    //data: $("#myform").serialize(),
                    error: erryFunction,  //错误执行方法
                    success: succFunction//成功执行方法
                });
                function erryFunction() {
                    PopupDia("请求失败", "error", "error");
                }
                function succFunction(data) {
                    //获取返回的json数据
                    //获取返回的json数据
                    var state = data.state;
                    var title = data.title;
                    var text = data.text;
                    var type = data.type;

                    PopupDia(title, text, type);
                }
            }
        });
    </script>
</body>
</html>